$('.owl-carousel').owlCarousel({
    loop:true,
    margin:7,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:4
        },
        1100:{
            items:8
        }
    }
})